FROM debian:12
RUN apt-get update && apt-get install -y --no-install-recommends \
      ruby ruby-dev build-essential curl dash shellcheck python3 \
 && gem install --no-document fpm \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
